name: test

on:
  pull_request:

jobs:
  test:
    name: Run Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - uses: notomo/action-setup-nvim-lua@v1
      - run: luarocks install vusted
      - run: luarocks install luacheck

      - name: install plenary.nvim
        if: matrix.os != 'windows-latest'
        run: |
            git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary

      - name: install plenary.nvim on windows
        if: matrix.os == 'windows-latest'
        run: |
            git clone --depth 1 https://github.com/nvim-lua/plenary.nvim .\plenary
            ls .\plenary
            ls .\plenary\lua

      - name: Run tests
        if: matrix.os != 'windows-latest'
        shell: bash
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
          VUSTED_ARGS: "--headless"
        run: |
            make test

      - name: Run tests
        if: matrix.os == 'windows-latest'
        shell: bash
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
          VUSTED_ARGS: "--headless"
        run: |
            make wintest
